In [1]:
from PIL import Image
import numpy as np

def image_to_matrix(image_path):
    # Open an image file
    with Image.open(image_path) as img:
        # Convert image to grayscale ('L' mode)
        img_gray = img.convert('L')
        
        # Convert image to a numpy array (matrix of pixel values)
        img_matrix = np.array(img_gray)
        
        return img_matrix

def print_matrix(matrix):
    # Print the matrix
    for row in matrix:
        print(' '.join(f'{pixel:3}' for pixel in row))

# Specify the path to your image file
image_path = 'DSAI4India/OCRApp/app-files/ocr/assets/images/Yashraj.jpeg'

# Convert image to matrix and print it
matrix = image_to_matrix(image_path)
print_matrix(matrix)


 60  76 108 130 139 155 158 140  84  76  90  92  93  98  99 120 173 152 129  97 109 118 131 122 120 123 128 135 143 150 156 159 146 149 154 158 160 159 156 154 160 160 159 158 157 156 156 155 161 161 162 162 163 164 165 165 163 163 163 164 164 165 165 165 163 157 132  94  65  57  55  51  57  95 114  90  61  52  46  35  42  42 112 118 109  71 104 145 180 182 182 188 178 123  76  73  73  34  36  79  93  73  63  69  43  46  47  42  44  55  52  35  16  56  99 108  79  42  20  15  21  69 113 137 140 116  90  88 103 107 117 127 142 131 107 121 127  93  63  73  96  89  79  93  94 117 109  96  94  64  46  70  78  91  90  68  50  46  45  41  33  36  38  35  29  28  33  39  69  67  61  44  46  50  55  94  90  42   9  12  37  69  74  53  38  44  36  28  31  23  12  17  20  19  17  15  13  11  10   9   9  10  11  12  14  15  16  17  14  22  30  32  30  32  40  49  33  17  20  27  26  40  52  43  46
 54  70 103 126 136 153 157 139  90  87 108 117 121 123 121 139 167 149 129 100 113 121 133 123 125 

In [3]:
import numpy as np

def build_vocab(text):
    # Create a set of unique characters
    unique_chars = sorted(set(text))
    # Create a mapping from character to index
    char_to_index = {char: idx for idx, char in enumerate(unique_chars)}
    return char_to_index

def text_to_one_hot(text, char_to_index):
    # Initialize an empty list for one-hot vectors
    one_hot_vectors = []
    vocab_size = len(char_to_index)
    
    for char in text:
        # Create a zero vector of length vocab_size
        one_hot_vector = np.zeros(vocab_size, dtype=int)
        # Set the appropriate index to 1
        if char in char_to_index:
            index = char_to_index[char]
            one_hot_vector[index] = 1
        one_hot_vectors.append(one_hot_vector)
    
    return np.array(one_hot_vectors)

def print_one_hot_vectors(one_hot_vectors):
    # Print the one-hot vectors
    for vector in one_hot_vectors:
        print(vector)

# Sample text
text = "hello my name is Yashraj and my College name is IIIT Dharwad"

# Build vocabulary from the text
char_to_index = build_vocab(text)

# Convert text to one-hot vectors
one_hot_vectors = text_to_one_hot(text, char_to_index)

# Print one-hot vectors
print_one_hot_vectors(one_hot_vectors)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0

In [11]:
!pip install opencv-python numpy


import cv2
import numpy as np

def video_to_frames(video_path):
    # Open video file
    cap = cv2.VideoCapture(video_path)
    frames = []
    
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)
    
    cap.release()
    return frames

def frames_to_matrix(frames):
    if not frames:
        return np.array([])
    
    # Convert first frame to grayscale to determine dimensions
    first_frame = cv2.cvtColor(frames[0], cv2.COLOR_BGR2GRAY)
    height, width = first_frame.shape
    num_frames = len(frames)
    
    # Initialize the matrix
    video_matrix = np.zeros((num_frames, height, width), dtype=np.uint8)
    
    for i, frame in enumerate(frames):
        # Convert frame to grayscale
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        # Store in the matrix
        video_matrix[i] = gray_frame
    
    return video_matrix

def print_video_matrix(video_matrix, num_frames=5):
    # Print a small portion of the video matrix for readability
    for i in range(min(num_frames, video_matrix.shape[0])):
        print(f'Frame {i}:')
        print(video_matrix[i])
        print()

# Specify the path to your video file
video_path = 'WIN_20240301_11_35_45_Pro.mp4'

# Extract frames from the video
frames = video_to_frames(video_path)

# Convert frames to a 4D matrix (num_frames, height, width)
video_matrix = frames_to_matrix(frames)

# Print a small portion of the video matrix
print_video_matrix(video_matrix)


Frame 0:
[[171 171 171 ... 245 245 245]
 [172 172 172 ... 245 245 245]
 [173 173 173 ... 245 245 245]
 ...
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]]

Frame 1:
[[171 171 171 ... 243 244 244]
 [172 172 172 ... 244 244 244]
 [173 173 173 ... 243 243 243]
 ...
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]]

Frame 2:
[[171 171 171 ... 244 244 243]
 [172 172 172 ... 244 244 244]
 [173 173 173 ... 244 244 244]
 ...
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]]

Frame 3:
[[171 171 171 ... 244 244 244]
 [172 172 172 ... 244 244 244]
 [173 173 173 ... 244 244 244]
 ...
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]
 [255 255 255 ...  52  52  52]]

Frame 4:
[[171 171 171 ... 244 244 244]
 [172 172 172 ... 244 244 244]
 [173 173 173 ... 244 244 244]
 ...
 [255 255 255 ...  51  51  51]
 [255 255 255 ...  51  51  51]
 [255 255 255 ...  51  